[project]
name = "portfolio-serverless-apis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
script = "src/main.py"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
]

